apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-gitops
    version: blue
  name: hello-gitops-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-gitops
      version: blue
  template:
    metadata:
      labels:
        app: hello-gitops
        version: blue
    spec:
      containers:
        - name: hello-gitops
          image: dreeeamcatcher/hello-gitops:blue
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 250m
              memory: 512Mi
          ports:
            - name: http
              containerPort: 8050
              