apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-gitops
    version: green
  name: hello-gitops-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-gitops
      version: green
  template:
    metadata:
      labels:
        app: hello-gitops
        version: green
    spec:
      containers:
        - name: hello-gitops
          image: dreeeamcatcher/hello-gitops
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 250m
              memory: 512Mi
          ports:
            - name: http
              containerPort: 8050
          readinessProbe:
            httpGet:
              path: /health
              port: 8050
            initialDelaySeconds: 15
            periodSeconds: 15
              