apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
namespace: python-app-blue
images:
- name: hello-gitops
  newName: dreeeamcatcher/hello-gitops
  newTag: 66ed9699fcdba9de2daf3113192d7f6e4520c3c2
