apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment-green.yaml
- service.yaml
images:
- name: hello-gitops
  newName: dreeeamcatcher/hello-gitops
  newTag: 24ca4e2b4eeaeb21600dd3a061b11c638389c154
