apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
namespace: python-app-green
images:
- name: hello-gitops
  newName: dreeeamcatcher/hello-gitops
  newTag: 8547122ac2ddfb03489ed0b7a4a917b3089d206b
